// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// buildCoralPlots
List buildCoralPlots(const DataFrame& rulesDF, int grid_size, Rcpp::CharacterVector edge_gradient, std::string edge_metric, Rcpp::Nullable<Rcpp::DataFrame> item_types, Rcpp::Nullable<Rcpp::DataFrame> type_colors);
RcppExport SEXP _niarules_buildCoralPlots(SEXP rulesDFSEXP, SEXP grid_sizeSEXP, SEXP edge_gradientSEXP, SEXP edge_metricSEXP, SEXP item_typesSEXP, SEXP type_colorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type rulesDF(rulesDFSEXP);
    Rcpp::traits::input_parameter< int >::type grid_size(grid_sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type edge_gradient(edge_gradientSEXP);
    Rcpp::traits::input_parameter< std::string >::type edge_metric(edge_metricSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::DataFrame> >::type item_types(item_typesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::DataFrame> >::type type_colors(type_colorsSEXP);
    rcpp_result_gen = Rcpp::wrap(buildCoralPlots(rulesDF, grid_size, edge_gradient, edge_metric, item_types, type_colors));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_niarules_buildCoralPlots", (DL_FUNC) &_niarules_buildCoralPlots, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_niarules(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
