# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
wrapped_buildRadialPlots <- function(rulesDF, grid_size) {
    .Call(`_niarules_wrapped_buildRadialPlots`, rulesDF, grid_size)
}

