# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Entry point for R to generate radial plot data from a set of association rules.
#'
#' @description This function takes a data frame of association rules and produces two data frames:
#' one for the nodes and one for the edges of a radial plot. It acts as a wrapper that:
#' \itemize{
#'    \item Converts the input R data frame to internal Rule objects.
#'    \item Constructs the radial layout by calling the lower-level `buildRadialPlots` function.
#'    \item Converts the resulting nodes and edges into R-compatible data frames.
#' }
#'
#' @param rulesDF A wide-format DataFrame representing association rules (as typically produced in R).
#' @param grid_size Number of grid cells per layout dimension to use during node positioning.
#'
#' @return A List containing two DataFrames:
#' \itemize{
#'    \item \code{edges}: DataFrame with start and end coordinates, line width, and color for each edge.
#'    \item \code{nodes}: DataFrame with position, radius, ID, and item label for each node.
#' }
#' @export
buildRadialPlots <- function(rulesDF, grid_size) {
    .Call(`_niarules_buildRadialPlots`, rulesDF, grid_size)
}

