# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
parse_rules_cpp <- function(rules_df) {
    .Call(`_niarules_parse_rules_cpp`, rules_df)
}

#' @title Entry point for R to generate coral plot data from a set of association rules.
#'
#' @description This function takes a data frame of association rules and produces two data frames:
#' one for the nodes and one for the edges of a coral plot. It acts as a wrapper that:
#' \itemize{
#'    \item Converts the input R data frame to internal Rule objects.
#'    \item Constructs the coral layout by calling the lower-level `buildCoralPlots` function.
#'    \item Converts the resulting nodes and edges into R-compatible data frames.
#' }
#'
#' @param rulesDF A wide-format DataFrame representing association rules (as typically produced in R).
#' @param grid_size Number of grid cells per layout dimension to use during node positioning.
#'
#' @return A List containing two DataFrames:
#' \itemize{
#'    \item \code{edges}: DataFrame with start and end coordinates, line width, and color for each edge.
#'    \item \code{nodes}: DataFrame with position, radius, ID, and item label for each node.
#' }
#' @export
buildCoralPlots <- function(rulesDF, grid_size, edge_gradient = as.character( c("#2c7bb6", "#d7191c")), edge_metric = "support", item_types = NULL, type_colors = NULL) {
    .Call(`_niarules_buildCoralPlots`, rulesDF, grid_size, edge_gradient, edge_metric, item_types, type_colors)
}

#' @export
build_layout_cpp <- function(parsed, grid_size, lhs_sort = "confidence", edge_metric = "support", edge_gradient = as.character( c("#2c7bb6","#d7191c"))) {
    .Call(`_niarules_build_layout_cpp`, parsed, grid_size, lhs_sort, edge_metric, edge_gradient)
}

